### ISSUE TITLE
Can't create a banner for my resource DelayedSpawners.

### ISSUE THREAD

**Issue by StjernholmPW** [MCBanners/website#11]
Can't create a banner for my resource DelayedSpawners.
Resource ID: 74577
Link: https://www.spigotmc.org/resources/delayedspawners-gui-editor.74577/

**Comment by simpleauthority** [comment]
It is too new and Spiget does not have your resource recorded yet. As soon as they do, it will be able to be created in MCBanners. Sorry, I can't do anything to speed up their crawling. :/

**Comment by simpleauthority** [comment]
Update. Might be a CF issue, I've reported this to Spiget.

**Comment by simpleauthority** [comment]
You should be able to generate a banner now.
