### ISSUE TITLE
"Apply to all" option for settings

### ISSUE THREAD

**Issue by Andre601** [MCBanners/website#176]
There should be a button to apply a specific setting to all parts of the banner. This would reduce the need of having to constantly switch tab and change the option such as font.

As an example, under "Resource name" would I now select "Jetbrains Mono". I would then click a button next to the dropdown that says "Apply to all text" or smth... This would now set the font to "Jetbrains Mono" for all displayed text parts.

**Comment by simpleauthority** [comment]
This is a good idea, thanks

**Comment by darbyjack** [comment]
Implemented via https://github.com/MCBanners/website/commit/e4140768b9057488b11f4d1a4a1ffc57d3325238
